services:
  PhilTenno\NewsPull\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'
    autowire: true
    autoconfigure: true

  PhilTenno\NewsPull\Controller\ImportController:
    tags: ['controller.service_arguments']

  PhilTenno\NewsPull\Service\Importer:
    arguments:
      $logger: '@logger'
      $params: '@parameter_bag'
